name: sendLove

on:
  push:
    branches:
      - pythonAutomate

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:      	
        python-version: '3.9'
        node-version: '16'  # Add this line to specify Node16

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python /home/runner/work/Personal-Practice/Personal-Practice/python-automation/sendSMS1.py

